-- MENU TREE sample menu data.
-- Run supabase/migrate_company_to_array.sql before this file.

insert into public.menus (
  name, category, price_from, price_to, weight, temperature, spicy_level,
  meal_time, company, main_ingredient, meal_format, description
) values
  ('김치찌개 정식', '한식', 9000, 12000, 'heavy', 'hot', 'medium', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '잘 익은 김치와 돼지고기를 넣어 든든하게 끓인 한 끼입니다.'),
  ('제육덮밥', '한식', 8500, 11000, 'heavy', 'hot', 'medium', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '매콤달콤한 제육볶음을 밥 위에 듬뿍 올린 메뉴입니다.'),
  ('불고기 비빔밥', '한식', 10000, 13000, 'heavy', 'mild', 'none', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '불고기와 여러 채소를 고추장에 비벼 먹는 균형 잡힌 식사입니다.'),
  ('콩나물국밥', '한식', 7500, 9500, 'heavy', 'hot', 'none', 'lunch', array['solo'], 'vegetable', 'one_dish', '뜨끈한 국물과 아삭한 콩나물이 속을 편안하게 채워 줍니다.'),
  ('닭갈비', '한식', 13000, 18000, 'heavy', 'hot', 'medium', 'dinner', array['pair', 'group'], 'meat', 'share', '매콤한 양념 닭고기와 채소를 함께 볶아 나눠 먹기 좋습니다.'),
  ('보쌈', '한식', 18000, 28000, 'heavy', 'hot', 'none', 'dinner', array['pair', 'group'], 'meat', 'share', '부드러운 수육을 김치와 곁들여 푸짐하게 즐기는 메뉴입니다.'),
  ('해물파전', '한식', 12000, 18000, 'heavy', 'hot', 'none', 'dinner', array['pair', 'group'], 'seafood', 'share', '바삭하게 부친 전 위에 해산물을 넉넉히 올린 메뉴입니다.'),
  ('비빔국수', '한식', 7500, 9500, 'light', 'cold', 'medium', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '새콤달콤한 양념과 쫄깃한 면이 입맛을 깨워 줍니다.'),
  ('냉면', '한식', 10000, 13000, 'light', 'cold', 'none', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '차가운 육수와 담백한 면을 산뜻하게 즐기는 메뉴입니다.'),
  ('떡볶이 모둠', '한식', 9000, 14000, 'adventurous', 'hot', 'medium', 'late', array['pair', 'group'], 'vegetable', 'share', '떡볶이와 튀김, 순대를 함께 나눠 먹는 늦은 시간 메뉴입니다.'),
  ('소고기 쌀국수', '아시아식', 9500, 12000, 'heavy', 'hot', 'none', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '맑고 진한 육수에 부드러운 소고기를 올린 쌀국수입니다.'),
  ('마라탕', '아시아식', 12000, 18000, 'adventurous', 'hot', 'high', 'dinner', array['solo', 'pair'], 'meat', 'one_dish', '원하는 재료를 골라 얼얼하고 화끈하게 즐기는 한 그릇입니다.'),
  ('마라샹궈', '아시아식', 18000, 30000, 'adventurous', 'hot', 'high', 'dinner', array['pair', 'group'], 'meat', 'share', '향신료에 볶은 재료를 여럿이 나눠 먹는 강렬한 메뉴입니다.'),
  ('새우 딤섬', '아시아식', 10000, 15000, 'light', 'hot', 'none', 'late', array['pair', 'group'], 'seafood', 'share', '뜨거운 딤섬을 여러 종류로 골라 나눠 먹기 좋습니다.'),
  ('연어 포케', '아시아식', 11000, 15000, 'light', 'cold', 'none', 'lunch', array['solo', 'pair'], 'seafood', 'one_dish', '신선한 연어와 채소, 곡물을 한 그릇에 담은 메뉴입니다.'),
  ('참치마요 삼각김밥', '아시아식', 2500, 4000, 'light', 'mild', 'none', 'late', array['solo'], 'seafood', 'handheld', '간편하게 들고 먹기 좋은 고소한 참치마요 삼각김밥입니다.'),
  ('치킨 타코', '양식', 9000, 14000, 'adventurous', 'mild', 'medium', 'late', array['solo', 'pair'], 'meat', 'handheld', '바삭한 치킨과 채소를 또르띠야에 담은 간편한 메뉴입니다.'),
  ('페퍼로니 피자', '양식', 16000, 24000, 'heavy', 'hot', 'none', 'dinner', array['pair', 'group'], 'meat', 'share', '짭짤한 페퍼로니와 치즈를 넉넉히 올린 나눔 메뉴입니다.'),
  ('버섯 크림 파스타', '양식', 13000, 17000, 'heavy', 'hot', 'none', 'dinner', array['solo', 'pair'], 'vegetable', 'one_dish', '고소한 크림소스와 버섯 향을 즐기는 부드러운 파스타입니다.'),
  ('해산물 토마토 파스타', '양식', 14000, 18000, 'heavy', 'hot', 'medium', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '토마토소스에 해산물을 더해 산뜻하고 진하게 완성한 파스타입니다.'),
  ('치킨 시저 샐러드', '양식', 9000, 12000, 'light', 'cold', 'none', 'lunch', array['solo'], 'meat', 'one_dish', '구운 치킨과 로메인, 치즈를 곁들인 가벼운 샐러드입니다.'),
  ('쉬림프 샌드위치', '양식', 8000, 11000, 'light', 'cold', 'none', 'lunch', array['solo', 'pair'], 'seafood', 'handheld', '새우와 아삭한 채소를 듬뿍 넣은 산뜻한 샌드위치입니다.'),
  ('치즈버거 세트', '양식', 9500, 13000, 'heavy', 'hot', 'none', 'late', array['solo', 'pair'], 'meat', 'handheld', '육즙 가득한 패티와 치즈로 간편하게 든든함을 채웁니다.'),
  ('나초 플래터', '양식', 12000, 18000, 'adventurous', 'hot', 'medium', 'late', array['pair', 'group'], 'vegetable', 'share', '바삭한 나초에 치즈와 살사를 올려 함께 즐기는 메뉴입니다.'),
  ('된장찌개 정식', '한식', 8500, 11000, 'heavy', 'hot', 'none', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '구수한 된장찌개와 반찬으로 편안하게 먹는 정식입니다.'),
  ('순대국', '한식', 9000, 11000, 'heavy', 'hot', 'none', 'lunch', array['solo'], 'meat', 'one_dish', '진한 국물에 순대를 넣어 든든하게 즐기는 국밥입니다.'),
  ('육개장', '한식', 9500, 12000, 'heavy', 'hot', 'medium', 'lunch', array['solo'], 'meat', 'one_dish', '칼칼한 국물과 찢은 소고기로 속을 데우는 메뉴입니다.'),
  ('갈비탕', '한식', 14000, 18000, 'heavy', 'hot', 'none', 'dinner', array['solo', 'pair'], 'meat', 'one_dish', '부드러운 갈비와 맑은 국물을 즐기는 특별한 한 끼입니다.'),
  ('돌솥비빔밥', '한식', 10000, 13000, 'heavy', 'hot', 'medium', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '바삭한 누룽지와 채소를 비벼 먹는 따뜻한 비빔밥입니다.'),
  ('오징어볶음', '한식', 12000, 16000, 'adventurous', 'hot', 'high', 'dinner', array['pair', 'group'], 'seafood', 'share', '매콤하게 볶은 오징어를 여럿이 나눠 먹기 좋습니다.'),
  ('물회', '한식', 15000, 20000, 'adventurous', 'cold', 'medium', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '새콤하고 시원한 육수에 회와 채소를 넣어 즐기는 메뉴입니다.'),
  ('생선구이 정식', '한식', 11000, 15000, 'heavy', 'hot', 'none', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '노릇하게 구운 생선과 반찬을 곁들인 정식입니다.'),
  ('김밥과 라면', '한식', 6500, 8500, 'light', 'hot', 'medium', 'late', array['solo', 'pair'], 'vegetable', 'handheld', '간단한 김밥과 뜨끈한 라면을 함께 즐기는 조합입니다.'),
  ('닭강정', '한식', 12000, 18000, 'adventurous', 'hot', 'medium', 'late', array['pair', 'group'], 'meat', 'share', '달콤매콤한 닭강정을 여럿이 나눠 먹기 좋습니다.'),
  ('족발', '한식', 25000, 35000, 'heavy', 'mild', 'none', 'dinner', array['pair', 'group'], 'meat', 'share', '쫀득한 족발을 채소와 곁들여 푸짐하게 즐깁니다.'),
  ('메밀전병', '한식', 7000, 10000, 'light', 'hot', 'medium', 'late', array['solo', 'pair'], 'vegetable', 'handheld', '메밀 피에 매콤한 속을 넣어 구운 간식 메뉴입니다.'),
  ('팥빙수', '한식', 9000, 14000, 'light', 'cold', 'none', 'late', array['pair', 'group'], 'vegetable', 'share', '시원한 얼음과 팥을 함께 나눠 먹는 달콤한 메뉴입니다.'),
  ('짜장면', '아시아식', 7000, 9000, 'heavy', 'hot', 'none', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '춘장 소스와 쫄깃한 면을 부담 없이 즐기는 메뉴입니다.'),
  ('짬뽕', '아시아식', 9000, 12000, 'heavy', 'hot', 'high', 'lunch', array['solo', 'pair'], 'seafood', 'one_dish', '해산물과 매콤한 국물이 어우러진 뜨거운 면 요리입니다.'),
  ('탕수육', '아시아식', 15000, 23000, 'heavy', 'hot', 'none', 'dinner', array['pair', 'group'], 'meat', 'share', '바삭한 튀김과 새콤달콤한 소스를 함께 즐깁니다.'),
  ('깐풍기', '아시아식', 16000, 22000, 'adventurous', 'mild', 'medium', 'dinner', array['pair', 'group'], 'meat', 'share', '매콤달콤한 소스에 닭튀김을 버무려 나눠 먹기 좋습니다.'),
  ('초밥 모둠', '아시아식', 14000, 22000, 'light', 'cold', 'none', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '다양한 생선 초밥을 산뜻하게 맛보는 메뉴입니다.'),
  ('회덮밥', '아시아식', 12000, 16000, 'light', 'cold', 'medium', 'lunch', array['solo', 'pair'], 'seafood', 'one_dish', '신선한 회와 채소를 매콤하게 비벼 먹는 덮밥입니다.'),
  ('돈카츠', '아시아식', 10000, 14000, 'heavy', 'hot', 'none', 'lunch', array['solo', 'pair'], 'meat', 'one_dish', '바삭한 돈카츠와 밥으로 든든하게 먹는 메뉴입니다.'),
  ('규동', '아시아식', 8500, 11000, 'heavy', 'hot', 'none', 'lunch', array['solo'], 'meat', 'one_dish', '달짝지근한 소고기를 밥 위에 올린 간편한 덮밥입니다.'),
  ('가라아게', '아시아식', 10000, 15000, 'adventurous', 'hot', 'none', 'late', array['pair', 'group'], 'meat', 'share', '바삭하게 튀긴 일본식 닭튀김을 나눠 먹습니다.'),
  ('오코노미야키', '아시아식', 12000, 16000, 'adventurous', 'hot', 'none', 'dinner', array['pair', 'group'], 'vegetable', 'share', '채소와 반죽을 철판에 구워 소스를 더한 메뉴입니다.'),
  ('야끼소바', '아시아식', 9000, 12000, 'heavy', 'hot', 'medium', 'late', array['solo', 'pair'], 'vegetable', 'one_dish', '불향 나는 볶음면을 빠르게 즐기는 메뉴입니다.'),
  ('월남쌈', '아시아식', 18000, 26000, 'light', 'cold', 'none', 'dinner', array['pair', 'group'], 'vegetable', 'share', '신선한 채소와 재료를 라이스페이퍼에 싸 먹습니다.'),
  ('팟타이', '아시아식', 11000, 15000, 'adventurous', 'hot', 'medium', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '새콤달콤한 소스와 새우가 어우러진 태국식 볶음면입니다.'),
  ('새우볶음밥', '아시아식', 9000, 12000, 'light', 'hot', 'none', 'lunch', array['solo', 'pair'], 'seafood', 'one_dish', '고슬고슬한 볶음밥에 새우를 더해 가볍게 즐깁니다.'),
  ('군만두', '아시아식', 10000, 15000, 'light', 'hot', 'none', 'late', array['pair', 'group'], 'meat', 'share', '노릇하게 구운 만두를 따뜻할 때 나눠 먹습니다.'),
  ('탄탄면', '아시아식', 10000, 13000, 'heavy', 'hot', 'high', 'lunch', array['solo'], 'meat', 'one_dish', '고소한 땅콩 소스와 매운 국물이 진한 면 요리입니다.'),
  ('베트남 반미', '아시아식', 7000, 10000, 'light', 'mild', 'medium', 'lunch', array['solo', 'pair'], 'meat', 'handheld', '바게트에 고기와 채소를 넣은 산뜻한 샌드위치입니다.'),
  ('치킨 커리', '아시아식', 11000, 15000, 'heavy', 'hot', 'medium', 'dinner', array['solo', 'pair'], 'meat', 'one_dish', '향신료가 어우러진 커리와 밥을 함께 즐깁니다.'),
  ('마파두부', '아시아식', 14000, 20000, 'adventurous', 'hot', 'medium', 'dinner', array['pair', 'group'], 'vegetable', 'share', '부드러운 두부와 매콤한 소스를 밥과 함께 나눠 먹습니다.'),
  ('알리오 올리오', '양식', 10000, 14000, 'light', 'hot', 'none', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '마늘과 올리브오일 향이 깔끔한 기본 파스타입니다.'),
  ('미트볼 토마토 파스타', '양식', 14000, 19000, 'heavy', 'hot', 'none', 'dinner', array['solo', 'pair'], 'meat', 'one_dish', '미트볼과 토마토소스를 더해 든든하게 즐기는 파스타입니다.'),
  ('스테이크', '양식', 25000, 40000, 'heavy', 'hot', 'none', 'dinner', array['pair'], 'meat', 'one_dish', '육즙 가득한 스테이크로 특별한 저녁을 즐깁니다.'),
  ('바비큐 립', '양식', 22000, 32000, 'heavy', 'hot', 'medium', 'dinner', array['pair', 'group'], 'meat', 'share', '달콤짭짤한 소스를 입힌 립을 푸짐하게 나눕니다.'),
  ('새우 로제 파스타', '양식', 13000, 17000, 'heavy', 'hot', 'none', 'dinner', array['solo', 'pair'], 'seafood', 'one_dish', '새우와 부드러운 로제소스를 곁들인 인기 파스타입니다.'),
  ('크림스프와 마늘빵', '양식', 7000, 10000, 'light', 'hot', 'none', 'lunch', array['solo'], 'vegetable', 'one_dish', '부드러운 크림스프와 마늘빵으로 가볍게 즐기는 메뉴입니다.'),
  ('리코타 샐러드', '양식', 10000, 14000, 'light', 'cold', 'none', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '신선한 채소와 리코타 치즈를 곁들인 산뜻한 샐러드입니다.'),
  ('연어 베이글', '양식', 9000, 13000, 'light', 'cold', 'none', 'lunch', array['solo', 'pair'], 'seafood', 'handheld', '훈제 연어와 크림치즈를 넣은 든든한 베이글입니다.'),
  ('핫도그', '양식', 5000, 8000, 'light', 'hot', 'none', 'late', array['solo'], 'meat', 'handheld', '따뜻한 소시지를 빵에 넣어 간편하게 즐깁니다.'),
  ('치킨 윙', '양식', 12000, 18000, 'adventurous', 'hot', 'high', 'late', array['pair', 'group'], 'meat', 'share', '매콤한 치킨 윙을 맥주와 함께 나눠 먹기 좋습니다.'),
  ('감바스', '양식', 15000, 22000, 'light', 'hot', 'medium', 'dinner', array['pair', 'group'], 'seafood', 'share', '올리브오일에 익힌 새우와 빵을 함께 곁들입니다.'),
  ('치즈스틱과 감자튀김', '양식', 8000, 12000, 'light', 'cold', 'none', 'late', array['pair', 'group'], 'vegetable', 'share', '치즈스틱과 감자튀김을 가볍게 나눠 먹는 사이드 메뉴입니다.'),
  ('퀘사디아', '양식', 10000, 15000, 'adventurous', 'hot', 'medium', 'late', array['solo', 'pair'], 'meat', 'handheld', '치즈와 고기를 또르띠야에 넣어 노릇하게 구웠습니다.'),
  ('부리토 볼', '양식', 11000, 15000, 'heavy', 'mild', 'medium', 'lunch', array['solo', 'pair'], 'vegetable', 'one_dish', '곡물과 채소, 콩을 한 그릇에 담은 든든한 메뉴입니다.'),
  ('오믈렛', '양식', 8500, 11000, 'light', 'hot', 'none', 'lunch', array['solo'], 'vegetable', 'one_dish', '부드러운 달걀과 채소를 넣어 가볍게 즐깁니다.'),
  ('프렌치토스트', '양식', 8000, 12000, 'light', 'mild', 'none', 'late', array['solo', 'pair'], 'vegetable', 'one_dish', '달콤하게 구운 빵으로 여유롭게 즐기는 브런치입니다.');
